project:
  type: book
  output-dir: docs

book:
  title: "Bash for Bioinformatics"
  author: "Ted Laderas"
  date: "10/2/2025"
  search: true
  repo-url: https://github.com/fhdsl/bash_for_bio
  chapters:
    - index.qmd
    - 00_prework.qmd
    - 01_basics.qmd
    - 01_scripting.qmd
    - 01_assignment.qmd
    - hpc-basics.qmd
    - 02_batch.qmd
    - 02_assignment.qmd
    - containers_reading.qmd
    - 03_containers.qmd
    - 03_assignment.qmd
    - pipes_json_reading.qmd
    - 04_containers_workflows.qmd
    - 04_assignment.qmd
    - testing.qmd
    - configuring.qmd
    - miscellaneous.qmd

glossary:
  path: glossary.yml
  popup: click
  show: true

format:
  html:
    theme:
      - cosmo
      - brand
  pdf: 
    toc: true
    number-sections: true
    colorlinks: true

