project:
  type: book
  output-dir: docs

book:
  title: "Bash for Bioinformatics"
  author: "Ted Laderas"
  date: "7/9/2025"
  chapters:
    - index.qmd
    - 01_basics.qmd
    - 02_scripting.qmd
    - hpc-basics.qmd
    - 03_batch.qmd
    - container-basics.qmd
    - 04_containers_workflows.qmd
    - testing.qmd
    - configuring.qmd
    - miscellaneous.qmd

glossary:
  path: glossary.yml
  popup: click
  show: true

format:
  html:
    theme:
      - cosmo
      - brand


