---
title: "W2: Batch Processing"
format: 
  revealjs:
    smaller: true
    scrollable: true
    echo: true
    embed-resources: true
output-location: fragment
---

## That `bwa` example from exercises...

## Today's Content

- Review of job submission on the cluster: <https://bashforbio.netlify.app/hpc-basics.html>
- Pipes: <https://bashforbio.netlify.app/pipes_json_reading.html>
- Batch processing on the cluster: <https://bashforbio.netlify.app/02_batch.html>

## Pipes

Last week, you saw

```         
samtools view -c CALU1_combined_final.sam > CALU1_combined_final.sam.counts.txt
```

. . .

```{mermaid}
graph LR
  A(STDIN) --> E[samtools view]
  E --> B(STDOUT)
  E --> C(STDERR)
```

. . .

Every program has three streams available to it: Standard In (STDIN), Standard Out (STDOUT), and Standard Error (STDERR)

. . .

- **STDIN** contains information that is directed to the input of a program (usually text output via STDOUT from another script). This includes arguments we pass onto the program.

- **STDOUT** contains information that is output of the script.

- **STDERR** contains any error messages that happened during the program run.

## Accessing Standard Out and Standard Error

Getting STDOUT:

```         
samtools view -c CALU1_combined_final.sam > CALU1_combined_final.sam.txt
```

Getting the STDERR:

```         
samtools view -c CALU1_combined_final.sam 2> CALU1_combined_final.sam.errors.txt
```

. . .

Getting both STDOUT and STDERR:

```         
samtools view -c CALU1_combined_final.sam > CALU1_combined_final.sam.txt 2> CALU1_combined_final.sam.errors.txt
```

. . .

More info here:

- <https://www.geeksforgeeks.org/linux-unix/input-output-redirection-in-linux/>

- <https://jeroenjanssens.com/dsatcl/chapter-2-getting-started>

## Chaining pipes

Taking the STDOUT of a program into the STDIN of another program:

```{mermaid}
graph LR
  E[cat READ.csv] --> B(STDOUT)
  B --> F{"|"}
  E --> C(STDERR)
  F --> D("grep dead ")
  D --> G[wc]
```

```         
cat READ.csv | grep dead
```

. . .

Other use cases:

- `cat READ.csv | grep "dead" | wc`

- `cat READ.csv | uniq | sort`

- `history | grep "sh"`

## Big example!

`run_bwa_and_sam_count.sh`

```         
#!/bin/bash
module load BWA/
module load SAMtools
input_fastq=${1}

# strip path and suffix
base_file_name="${input_fastq%.fastq}"
base_file_name=${base_file_name##*/}
#variables for bwa mem read group
sample_name="SM:${base_file_name}"
read_group_id="ID:${base_file_name}"
platform_info="PL:Illumina"
ref_fasta_local="/shared/biodata/reference/iGenomes/Homo_sapiens/UCSC/hg19/Sequence/BWAIndex/genome.fa"

echo "running $input_fastq"

bwa mem \
      -p -v 3 -M \
      -R "@RG\t${read_group_id}\t${sample_name}\t${platform_info}" \
      "${ref_fasta_local}" "${input_fastq}" | \
samtools sort > ${base_file_name}.bam

samtools index ${base_file_name}.bam

samtools view -c ${base_file_name}.bam > \
      ${base_file_name}.bam.counts.txt

module purge
```

## **Using `for` loops to cycle through files**

When we want to process many files in the same way:

. . .

```         
cd bash_for_bio/scripts/week2
```

```         
for file in HCC4006_final.fastq CALU1_combined_final.fastq
do
  echo "Word count of ${file}:"
  wc $file
done
```

. . .

- At each iteration, within the `do` and `done` blocks of code, the variable `file` is updated with the list of characters described in `in` statement.

- Within the `do` and `done` blocks of code, we print the value of `file` look at the word count of `file` via the `wc` command.

## **Using wildcards to determine files to loop through**

Instead of writing down all the files to loop through, we can use wildcards:

. . .

- `*` wildcard: any number of characters
  - `*.pdf` any number of characters that ends with `.pdf`
  - `style*` starts with `style`, and ends with any number of characters.
  - `*mouse*` any number of characters that continues to `mouse`, and then any number of characters
  - `*` all files

Other types of wildcards here: <https://www.marquette.edu/high-performance-computing/tips-and-tricks.php>

. . .

```         
for file in *.fastq
do
  echo "Word count of ${file}:"
  wc $file
done
```

. . .

Example: `./batch_on_rhino.sh`

## Launching jobs on the cluster

```         
sbatch batch_on_rhino.sh
```

. . .

Options for `sbatch`

- `-c` request a number of processors per task (default 1)

- `-p` change the partition

- `-t` request a certain amount of time for the job.

- `-J` name a job

<https://sciwiki.fredhutch.org/scicomputing/compute_jobs/>

. . .

You can save these options within the bash script via `#SBATCH` header, such as:

```         
#!/bin/bash
#SBATCH -c 2
for file in *.fastq
do
  wc $file
done
```

. . .

But how do we do across multiple compute nodes at once?

## Batching on the cluster

```         
#!/bin/bash
#SBATCH --nodes=3
#SBATCH --array=1-3
sleep 30
echo "${SLURM_ARRAY_TASK_ID} job"
```

If we launch this job, it will run 3 instances on 3 different computing nodes.

. . .

Each instance will `sleep 30` and then print out their array task ID, which will be 1, 2, and 3.

. . .

```{mermaid}
graph TD
  A["sbatch sbatch_test.sh"] --"1"--> B
  B["echo 1 job"]
  A --"2"--> C["echo 2 job"]
  A --"3"--> D["echo 3 job"]
```

. . .

Try running `sbatch sbatch_test.sh`

## Batching a selection of files on the cluster

```         
#!/bin/bash
#SBATCH --array=1-3

file_array=(../../data/*.fastq)   
ind=$((SLURM_ARRAY_TASK_ID-1))
echo "$ind"
current_file=${file_array[$ind]}
echo "$current_file"
# execute the `run_bwa.sh` script on $current_file
./run_bwa.sh $current_file
```

. . .

This requires you knowing the number of fastq files in advance.

Try it out: `sbatch run_sbatch.sh`

## Calculating the number of files in advance

Count the number of files, minus one, and give it to `--array` option:

```         
file_array=(../../data/*.fastq)   
num_files=${#file_array[@]}
max_index=$((num_files - 1))
sbatch --array=0-${max_index} run_sbatch2.sh
```

. . .

`run_sbatch2.sh` is almost the same as before, but without `#SBATCH --array=1-3` hard-coded:

```         
#!/bin/bash

file_array=(../../data/*.fastq)   
ind=$((SLURM_ARRAY_TASK_ID-1))
echo "$ind"
current_file=${file_array[$ind]}
echo "$current_file"
# execute the `run_bwa.sh` script on $current_file
./run_bwa.sh $current_file
```

## Appendix: bash symbols

- `[ ]` accesses elements of an array

- `${ }` references a variable

- `( )` subshell execution to run a quick command

- `$( )` subshell execution to run a quick command, with output to be stored in a variable

- `(( ))` integer arithmetic

- `$(( ))` integer arithmetic, with output to be stored in a variable
